export enum OrderStatus {
  draft = 'draft',
  received = 'received',
  processed = 'processed',
  confirmed = 'confirmed',
  fake = 'fake order',
  duplicate = 'duplicate',
  paymentPending = 'payment pending',
  noPick = 'no pick',
  cancel = 'cancel',
  inBookingQueue = 'in booking queue',
  booked = 'booked',
  bookingError = 'booking error',
  bookingCanceled = 'booking canceled',
  dispatched = 'dispatched',
  inTransit = 'in transit',
  delivered = 'delivered',
  inReturnProcess = 'in return process',
  returned = 'returned',
}

export enum OrderEvents {
  received = 'order received from shopify store {store}',
  created = 'order created',
  updated = 'order updated',
  statusUpdatedFromTo = 'order status updated, {from} -> {to}',
  statusUpdatedTo = 'order status updated to {status}',
  paymentAdded = 'payment added',
  itemAdded = 'new item added',
  itemUpdated = 'item updated',
  itemDeleted = 'item deleted',
  deleted = 'order deleted',
  booked = 'order booked with {courier} using account {account}',
  bookingFailed = 'order booking failed with {courier} using account {account}, error -> {error}',
  bookingStopped = 'user action of booking order stopped because order is already booked or in booking queue. Tried to book with {courier} using account {account}',
}
